config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'meetings#index'
  resources :meetings do
    resources :comments, only: :create
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :meeting  # tweetsテーブルとのアソシエーション
  belongs_to :user  # usersテーブルとのアソシエーション
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :comments

  validates :name, length:{ maximum: 30 }, presence: true
  validates :start_time, presence: true
  validates :image, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments

  validates :nickname, presence: true, length: { maximum: 6 }
  validates :email, presence: true
  validates :password, presence: true, format: { with:  /\A(?=.*?[a-zA-Z])(?=.*?\d)[a-zA-Z\d]{6,100}+\z/ }, on: :create
end

app/models/users.rb
class Users < ApplicationRecord
  has_many : meetings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    respond_to do |format|
      format.html { redirect_to meeting_path(params[:meeting_id])  }
      format.json
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, meeting_id: params[:meeting_id])
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, except: [:index]
  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.order('created_at DESC')
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @comment = Comment.new
    @comments = @meeting.comments.includes(:user)
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time, :image)
    end

    def move_to_index
      unless user_signed_in?
        redirect_to action: :index
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Calendar
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body
    
    %header.header
      .header__bar.row
        - if user_signed_in?
          .user_nav.grid-6
            = link_to "ログアウト", destroy_user_session_path, method: :delete
        - else
          .grid-6
            = link_to "ログイン", new_user_session_path, class: "post"
            = link_to "新規登録", new_user_registration_path, class: "post"
    = render 'layouts/notifications'
    = yield

app/views/meetings/_footer.html.haml
.container
  .row
    .col-md-12
      %p.copyright
        ©️
        %a#year 2020
        MANEJA

app/views/meetings/_form.html.haml
= form_with(model: meeting, local: true) do |form|
  - if meeting.errors.any?
    #error_explanation
      %h2
        = pluralize(meeting.errors.count, "error")
        prohibited this meeting from being saved:
      %ul
        - meeting.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :スケジュールを入力してください
    = form.text_field :"name"
  .field
    = form.label :開始時間を入力してください
    = form.datetime_select :start_time
    = form.label "画像をアップロードしてください"
    %label{class:"image"}
      ファイルを選択
      = form.file_field :image, {class:"file"}
      - if @meeting.image?
        = image_tag @meeting.image.url

  .actions
    = form.submit class:"btn"

app/views/meetings/edit.html.haml
%h1 EDIT SCHEDULE
= render 'form', meeting: @meeting
= link_to '詳細', @meeting, {class:"backbtn"}
= link_to 'Back', meetings_path, {class:"backbtn"}
.footer
  = render 'footer'

app/views/meetings/index.html.haml
%h1 MANEJA
.first-view
  %img.top-image{:alt => "トップ画面", :src => "/assets/techou.jpg"}/
  .carousel-caption
    %span.h1 MANEJA
    %p スケジュール調整を、もっと楽に。
.secound-view
  %tr
    %th SCHEDULE LIST
  %th{:colspan => "3"}
- if user_signed_in?
  %table
    %tbody{class:"schedule_list"}
      - @meetings.each do |meeting|
        %tr{class:"schedule_list_list"}
          %td= meeting.name
          %td= meeting.start_time.strftime("%Y-%m-%d %H:%M")
          %td= link_to '', meeting,{class:"fas fa-list my-white fa-2x"}
          %td= link_to '', edit_meeting_path(meeting),{class:"fas fa-edit my-white fa-2x"}
          %td= link_to '', meeting, method: :delete, data: { confirm: 'Are you sure?' },class:"far fa-trash-alt my-white fa-2x"
%br/
%a.btn-square{:href => "/meetings/new"} NEW
= month_calendar events: @meetings do |date, meetings|
  = date.day
  - if user_signed_in?
    - meetings.each do |meeting|
      %div
        = link_to meeting.name,meeting
.footer
  = render 'footer'

app/views/meetings/new.html.haml
%h1 NEW SCHEDULE
= render 'form', meeting: @meeting
= link_to 'Back', meetings_path, {class:"backbtn"}
.footer
  = render 'footer'

app/views/meetings/show.html.haml
%p#notice= notice
%h1 DETAIL
%p1
  %strong Name:
  = @meeting.name
%p1
  %strong Start time:
  = @meeting.start_time
%p2
  - if @meeting.image?
    = image_tag @meeting.image.url
.container
  - if current_user
    = form_with model: [@meeting, @comment], local: true,class: "new_comment" do |form|
      = form.text_area :text, placeholder: "コメントする", rows: "3"
      = form.submit "SEND",{class:"sendbtn"}
  - else
    %strong
      %p ※※※ コメントの投稿には新規登録/ログインが必要です ※※※
.comments
  %h4 ＜コメント一覧＞
  - if @comments
    - @comments.each do |comment|
      %p
        %strong
          = link_to comment.user.nickname, "/users/#{comment.user_id}"
          ：
        = comment.text

= link_to '編集', edit_meeting_path(@meeting),{class:"backbtn"}
= link_to 'Back', meetings_path, {class:"backbtn"}

.footer
  = render 'footer'

app/views/simple_calendar/_calendar.html.haml
.simple-calendar
  .calendar-heading
    = link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view
    %span.calendar-title
      = t('date.month_names')[start_date.month]
      = start_date.year
    = link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view
  %table.table.table-striped
    %thead
      %tr
        - date_range.slice(0, 7).each do |day|
          %th= t('date.abbr_day_names')[day.wday]
    %tbody
      - date_range.each_slice(7) do |week|
        = content_tag :tr, class: calendar.tr_classes_for(week) do
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block)
                - capture_haml(day, sorted_events.fetch(day, []), &passed_block)
              - else
                - passed_block.call day, sorted_events.fetch(day, [])

app/views/simple_calendar/_month_calendar.html.haml
.simple-calendar
  .calendar-heading
    = link_to t('simple_calendar.previous', default: ''), calendar.url_for_previous_view,{class:"fas fa-angle-double-left fa-3x"}
    %span.calendar-title
      = t('date.month_names')[start_date.month]
      = start_date.year
    = link_to t('simple_calendar.next', default: ''), calendar.url_for_next_view,{class:"fas fa-angle-double-right fa-3x"}
  %table.table.table-striped
    %thead
      %tr
        - date_range.slice(0, 7).each do |day|
          %th= t('date.abbr_day_names')[day.wday]
    %tbody
      - date_range.each_slice(7) do |week|
        %tr
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block)
                - capture_haml(day, sorted_events.fetch(day, []), &passed_block)
              - else
                - passed_block.call day, sorted_events.fetch(day, [])

app/views/simple_calendar/_week_calendar.html.haml
.simple-calendar
  .calendar-heading
    = link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view
    - if calendar.number_of_weeks == 1
      %span.calendar-title
        Week #{calendar.week_number}
    - else
      %span.calendar-title
        Week #{calendar.week_number} - #{calendar.end_week}
    = link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view
  %table.table.table-striped
    %thead
      %tr
        - date_range.slice(0, 7).each do |day|
          %th= t('date.abbr_day_names')[day.wday]
    %tbody
      - date_range.each_slice(7) do |week|
        %tr
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block)
                - capture_haml(day, sorted_events.fetch(day, []), &passed_block)
              - else
                - passed_block.call day, sorted_events.fetch(day, [])